import { BookOpen, Flag, Target } from "lucide-react";
import { EmptyState } from "@/components/data-display/empty-state";
import type { ApplicationDetail } from "@/features/admin/applications/applications.types";

export function CareerPathTab({ application }: { application: ApplicationDetail }) {
  if (!application.careerPath.length) return <EmptyState title="Chưa có lộ trình nghề nghiệp" description={application.aiStatus === "FAILED" ? "Lộ trình không được tạo do quy trình AI thất bại." : "Lộ trình sẽ xuất hiện sau khi AI xử lý hoàn tất."} />;
  return <div className="grid gap-7 lg:grid-cols-[0.72fr_1.28fr]">
    <section><p className="admin-kicker text-brand">Trọng tâm phát triển</p><h3 className="mt-1 text-lg font-semibold text-ink">Năng lực cần đầu tư</h3><div className="mt-4 space-y-2">{application.growthAreas.map((area, index) => <div key={area} className="flex items-center gap-3 rounded-[9px] border border-border p-3"><span className="grid size-7 place-items-center rounded-full bg-signal/45 text-xs font-semibold text-brand">{index + 1}</span><span className="text-sm text-ink">{area}</span></div>)}</div><div className="mt-5 rounded-[9px] bg-surface-soft p-4"><p className="flex items-center gap-2 text-xs font-semibold text-ink"><BookOpen className="size-4 text-brand" />Tài nguyên gợi ý</p><p className="mt-2 text-xs leading-5 text-muted">Khóa học nội bộ, dự án thực hành và hoạt động mentoring theo từng giai đoạn.</p></div></section>
    <ol className="relative space-y-0">{application.careerPath.map((phase, index) => <li key={phase.title} className="relative grid grid-cols-[42px_1fr] gap-4 pb-7 last:pb-0">{index < application.careerPath.length - 1 ? <span className="absolute left-5 top-10 h-[calc(100%-18px)] w-px bg-border" /> : null}<span className="relative z-10 grid size-10 place-items-center rounded-full border border-brand/20 bg-surface text-brand"><Flag className="size-4" /></span><div className="rounded-[10px] border border-border bg-surface p-4"><div className="flex flex-wrap items-start justify-between gap-2"><h3 className="text-sm font-semibold text-ink">{phase.title}</h3><span className="rounded-full bg-surface-soft px-2.5 py-1 text-[10px] font-semibold text-muted">{phase.duration}</span></div><p className="mt-2 flex gap-2 text-xs leading-5 text-muted"><Target className="mt-0.5 size-3.5 shrink-0 text-brand" />{phase.objective}</p><ul className="mt-3 space-y-1.5 border-t border-border pt-3 text-xs text-muted">{phase.activities.map((activity) => <li key={activity}>· {activity}</li>)}</ul></div></li>)}</ol>
  </div>;
}
