import { AlertTriangle, Bot, CheckCircle2, Clock3, SearchX, ShieldAlert } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { StatusDot } from "@/components/ui/status-dot";
import { aiStatusMap } from "@/config/status";
import type { CompetencyEvidence, HrApplicationDetail } from "@/features/hr/applications/applications.types";

export function MatchingEvidencePanel({ application }: { application: HrApplicationDetail }) {
  if (application.aiStatus !== "COMPLETED") return <AiUnavailableState application={application} />;
  const lowConfidence = application.aiConfidence < 0.75 || application.needsReview;
  return <section className="overflow-hidden rounded-[12px] border border-border bg-[#13291f] text-white">
    <div className="flex flex-col gap-5 border-b border-white/15 p-5 sm:flex-row sm:items-start sm:justify-between"><div><p className="admin-kicker text-[#91a398]">Phân tích hỗ trợ</p><h2 className="mt-2 flex items-center gap-2 text-lg font-semibold"><Bot className="size-5 text-signal" /> Kết quả đối sánh AI</h2><p className="mt-2 max-w-xl text-xs leading-5 text-[#a5b6ac]">AI tổng hợp tín hiệu từ CV. Kết quả không thay thế đánh giá và quyết định của HR.</p></div><div className="rounded-[10px] border border-white/15 bg-white/[0.04] px-5 py-3 text-right"><p className="text-[11px] text-[#a5b6ac]">Điểm tổng quan</p><p className="mt-1 text-3xl font-semibold tabular-nums text-signal">{application.matchScore}<span className="text-sm text-[#a5b6ac]">/100</span></p><p className="mt-1 text-[11px] text-[#a5b6ac]">Độ tin cậy {Math.round(application.aiConfidence * 100)}%</p></div></div>
    {lowConfidence ? <div className="flex gap-3 border-b border-warning/25 bg-warning/[0.08] px-5 py-4"><AlertTriangle className="mt-0.5 size-5 shrink-0 text-signal" /><div><p className="text-sm font-semibold">Kết quả cần được đối chiếu</p><p className="mt-1 text-xs leading-5 text-[#c2cdc6]">Độ tin cậy thấp hoặc dữ liệu trích xuất có cảnh báo. Hãy đọc CV trước khi thay đổi trạng thái tuyển dụng.</p></div></div> : null}
    {application.scoreBreakdown ? <div className="grid gap-px border-b border-white/15 bg-white/15 sm:grid-cols-3"><Score label="Năng lực chuyên môn" value={application.scoreBreakdown.hardSkills} /><Score label="Kỹ năng mềm" value={application.scoreBreakdown.softSkills} /><Score label="Kinh nghiệm" value={application.scoreBreakdown.experience} /></div> : null}
    <div className="space-y-4 p-5 sm:p-6"><div className="flex items-center justify-between"><h3 className="text-sm font-semibold">Bằng chứng theo năng lực</h3><span className="text-xs text-[#91a398]">{application.competencyEvidence.length} tiêu chí</span></div><div className="overflow-hidden rounded-[10px] border border-white/20">{application.competencyEvidence.map((item) => <EvidenceRow key={item.competencyId} item={item} />)}</div>{application.aiRecommendation ? <div className="rounded-[9px] bg-white/[0.045] p-4"><p className="text-xs font-semibold text-signal">Gợi ý cho HR</p><p className="mt-2 text-sm leading-6 text-[#c2cdc6]">{application.aiRecommendation}</p></div> : null}</div>
  </section>;
}

function Score({ label, value }: { label: string; value: number }) { return <div className="bg-[#13291f] px-5 py-4"><div className="flex items-end justify-between"><p className="text-xs text-[#a5b6ac]">{label}</p><p className="font-semibold tabular-nums">{value}%</p></div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-signal" style={{ width: `${value}%` }} /></div></div>; }

function EvidenceRow({ item }: { item: CompetencyEvidence }) {
  const presentation = item.evidenceStatus === "SUPPORTED" ? { icon: CheckCircle2, label: "Có bằng chứng", tone: "success" as const } : item.evidenceStatus === "PARTIAL" ? { icon: AlertTriangle, label: "Bằng chứng một phần", tone: "warning" as const } : { icon: SearchX, label: "Chưa tìm thấy đủ", tone: "neutral" as const };
  const Icon = presentation.icon;
  return <article className="border-b border-white/15 p-4 last:border-0"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p className="font-semibold">{item.name}</p><div className="mt-2 flex flex-wrap gap-2 text-[11px] text-[#91a398]"><span>Cấp {item.requiredLevel}/5</span><span>·</span><span>Trọng số {item.weight}%</span>{item.mandatory ? <Badge tone="signal">Bắt buộc</Badge> : null}</div></div><Badge tone={presentation.tone}><Icon className="mr-1 size-3" />{presentation.label}</Badge></div><p className="mt-3 text-xs leading-5 text-[#b8c5bd]">{item.evidence}</p><p className="mt-2 text-[11px] text-[#82968a]">Độ tin cậy bằng chứng: {item.confidence === "HIGH" ? "Cao" : item.confidence === "MEDIUM" ? "Trung bình" : "Thấp"}</p></article>;
}

function AiUnavailableState({ application }: { application: HrApplicationDetail }) {
  const status = aiStatusMap[application.aiStatus];
  const failed = application.aiStatus === "FAILED";
  return <section className="rounded-[12px] border border-border bg-surface p-5 sm:p-6"><div className="flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between"><div className="flex gap-4">{failed ? <ShieldAlert className="size-7 text-danger" /> : <Clock3 className="size-7 text-info" />}<div><p className="admin-kicker text-muted">Phân tích hỗ trợ</p><h2 className="mt-2 text-lg font-semibold text-ink">{failed ? "AI chưa thể hoàn thành" : "Kết quả AI chưa sẵn sàng"}</h2><p className="mt-2 max-w-xl text-sm leading-6 text-muted">{failed ? application.errorCode === "INVALID_FILE" ? "Tệp CV có thể bị hỏng hoặc sai định dạng. HR vẫn có thể đánh giá thủ công và liên hệ ứng viên để tải lại tệp." : "Hồ sơ đã được chuyển sang hàng đợi hỗ trợ của Admin. HR vẫn có thể đọc hồ sơ và đưa ra đánh giá thủ công." : "Hệ thống đang tiếp nhận hoặc xử lý CV. Bạn có thể đọc thông tin hồ sơ trong lúc chờ kết quả."}</p></div></div><StatusDot label={status.label} tone={status.tone} /></div>{application.errorMessage ? <p className="mt-5 rounded-[9px] bg-danger/[0.05] p-3 text-xs leading-5 text-danger">{application.errorMessage}</p> : null}<p className="mt-5 border-t border-border pt-4 text-xs leading-5 text-muted">Trạng thái AI và trạng thái tuyển dụng là hai luồng độc lập. AI thất bại không đồng nghĩa hồ sơ không phù hợp.</p></section>;
}
