package com.tttn.backend_core.entity;

public enum ActivityKind {
  USER_STATUS_CHANGED,
  STAFF_PROFILE_SYNCED,
  JOB_CREATED,
  JOB_UPDATED,
  JOB_STATUS_CHANGED,
  APPLICATION_SUBMITTED,
  APPLICATION_STATUS_CHANGED,
  AI_SCORING_STARTED,
  AI_SCORING_COMPLETED,
  AI_SCORING_FAILED,
  KNOWLEDGE_CHANGED
}
