"use client";

import { useState } from "react";
import { Edit2, Plus, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { useDeletePedigree, usePedigreeGroups, usePedigrees, useSavePedigree, useSavePedigreeGroup } from "../knowledge-base.queries";
import type { PedigreeEntity, PedigreeGroup } from "../knowledge-base.types";

const sourceLabel = { EDUCATION: "Học vấn", EXPERIENCE: "Kinh nghiệm", CERTIFICATION: "Chứng chỉ", GPA: "GPA" } as const;

export function PedigreeManager({ mode }: { mode: "organizations" | "groups" }) {
  const pedigrees = usePedigrees();
  const groups = usePedigreeGroups();
  const deleteOrg = useDeletePedigree();
  const [editingOrg, setEditingOrg] = useState<PedigreeEntity | null | undefined>();
  const [editingGroup, setEditingGroup] = useState<PedigreeGroup | null | undefined>();
  if (pedigrees.isLoading || groups.isLoading) return <div className="rounded-xl border border-border bg-surface p-6 text-sm text-muted">Đang tải catalog đối chiếu…</div>;
  if (mode === "organizations") return <section className="rounded-xl border border-border bg-surface"><header className="flex items-center justify-between border-b border-border p-4"><div><h2 className="font-semibold text-ink">Tổ chức và alias</h2><p className="mt-1 text-sm text-muted">Alias giúp nhận diện các cách viết khác nhau của cùng một tổ chức trong CV.</p></div><Button size="sm" onClick={() => setEditingOrg(null)}><Plus className="size-4" /> Thêm tổ chức</Button></header><div className="divide-y divide-border">{(pedigrees.data ?? []).map((item) => <article key={item.id} className="flex items-start justify-between gap-4 p-4"><div><p className="font-medium text-ink">{item.name} <span className="ml-2 text-xs text-muted">{item.type} · {item.rank}</span></p><p className="mt-1 text-xs text-muted">Alias: {item.aliases?.join(" · ") || "Chưa có"}</p></div><div className="flex"><Button variant="ghost" size="sm" onClick={() => setEditingOrg(item)}><Edit2 className="size-4" /></Button><Button variant="ghost" size="sm" className="text-danger" onClick={() => { if (confirm(`Vô hiệu hóa ${item.name}?`)) deleteOrg.mutate(item.id); }}><Trash2 className="size-4" /></Button></div></article>)}{!pedigrees.data?.length && <p className="p-6 text-center text-sm text-muted">Chưa có tổ chức.</p>}</div><OrganizationDialog key={editingOrg?.id ?? "new"} item={editingOrg} onClose={() => setEditingOrg(undefined)} /></section>;
  return <section className="rounded-xl border border-border bg-surface"><header className="flex items-center justify-between border-b border-border p-4"><div><h2 className="font-semibold text-ink">Nhóm tổ chức đối chiếu</h2><p className="mt-1 text-sm text-muted">Một nhóm là tập tổ chức mà quy tắc dùng để kiểm tra bằng chứng trong CV.</p></div><Button size="sm" onClick={() => setEditingGroup(null)}><Plus className="size-4" /> Thêm nhóm</Button></header><div className="grid gap-3 p-4 sm:grid-cols-2">{(groups.data ?? []).map((group) => <article key={group.id} className="rounded-lg border border-border bg-surface-soft p-4"><div className="flex justify-between gap-2"><div><h3 className="font-medium text-ink">{group.name}</h3><p className="mt-1 text-xs text-muted">{sourceLabel[group.evidenceSource]} · {group.memberIds.length} tổ chức</p><code className="mt-2 block text-xs text-faint">{group.code}</code></div><Button variant="ghost" size="sm" onClick={() => setEditingGroup(group)}><Edit2 className="size-4" /></Button></div></article>)}</div><GroupDialog key={editingGroup?.id ?? "new"} item={editingGroup} organizations={pedigrees.data ?? []} onClose={() => setEditingGroup(undefined)} /></section>;
}

function OrganizationDialog({ item, onClose }: { item: PedigreeEntity | null | undefined; onClose: () => void }) {
  const save = useSavePedigree(); const deleteOrg = useDeletePedigree();
  const [data, setData] = useState(() => item ? { name: item.name, type: item.type, rank: item.rank, domain: item.domain, country: item.country, aliases: item.aliases.filter((alias) => alias !== item.name).join("\n") } : { name: "", type: "UNIVERSITY", rank: "TIER_2", domain: "ALL", country: "VN", aliases: "" });
  if (item === undefined) return null;
  const set = (key: keyof typeof data, value: string) => setData((current) => ({ ...current, [key]: value }));
  return <Dialog open onOpenChange={(open) => !open && onClose()}><DialogContent title={item ? "Chỉnh sửa tổ chức" : "Thêm tổ chức"} className="max-w-xl"><DialogHeader><DialogTitle>{item ? "Chỉnh sửa tổ chức" : "Thêm tổ chức"}</DialogTitle></DialogHeader><div className="space-y-4 py-4"><div><label className="mb-1 block text-sm font-medium">Tên tổ chức</label><Input value={data.name} onChange={(e) => set("name", e.target.value)} /></div><div className="grid grid-cols-2 gap-3"><Select label="Loại" value={data.type} onChange={(v) => set("type", v)} options={[["UNIVERSITY", "Trường học"], ["COMPANY", "Công ty"], ["AGENCY", "Agency"]]} /><Select label="Hạng" value={data.rank} onChange={(v) => set("rank", v)} options={[["INTERNATIONAL", "Quốc tế"], ["TIER_1", "Tier 1"], ["TIER_2", "Tier 2"], ["TIER_3", "Tier 3"]]} /></div><div><label className="mb-1 block text-sm font-medium">Alias</label><Textarea value={data.aliases} onChange={(e) => set("aliases", e.target.value)} placeholder="Mỗi alias một dòng, ví dụ: HCMUT&#10;Đại học Bách Khoa TP.HCM" rows={4} /><p className="mt-1 text-xs text-muted">Tên chính tự được thêm vào danh sách alias.</p></div><div className="flex justify-end gap-2"><Button variant="secondary" onClick={onClose}>Hủy</Button>{item && <Button variant="ghost" className="text-danger" onClick={() => { if (confirm(`Vô hiệu hóa ${item.name}?`)) deleteOrg.mutateAsync(item.id).then(onClose); }}>Vô hiệu hóa</Button>}<Button loading={save.isPending} onClick={() => save.mutateAsync({ id: item?.id, data: { ...data, aliases: data.aliases.split("\n").map((alias) => alias.trim()).filter(Boolean) } }).then(() => { toast.success("Đã lưu tổ chức"); onClose(); })}>Lưu</Button></div></div></DialogContent></Dialog>;
}

function GroupDialog({ item, organizations, onClose }: { item: PedigreeGroup | null | undefined; organizations: PedigreeEntity[]; onClose: () => void }) {
  const save = useSavePedigreeGroup(); const [data, setData] = useState(() => item ? { code: item.code, name: item.name, evidenceSource: item.evidenceSource, memberIds: item.memberIds } : { code: "", name: "", evidenceSource: "EDUCATION", memberIds: [] });
  if (item === undefined) return null;
  const toggle = (id: string) => setData((current) => ({ ...current, memberIds: current.memberIds.includes(id) ? current.memberIds.filter((value) => value !== id) : [...current.memberIds, id] }));
  return <Dialog open onOpenChange={(open) => !open && onClose()}><DialogContent title={item ? "Chỉnh sửa nhóm" : "Thêm nhóm"} className="max-w-xl"><DialogHeader><DialogTitle>{item ? "Chỉnh sửa nhóm đối chiếu" : "Thêm nhóm đối chiếu"}</DialogTitle></DialogHeader><div className="space-y-4 py-4"><div className="grid grid-cols-2 gap-3"><div><label className="mb-1 block text-sm font-medium">Tên nhóm</label><Input value={data.name} onChange={(e) => setData({ ...data, name: e.target.value })} /></div><div><label className="mb-1 block text-sm font-medium">Mã nhóm</label><Input value={data.code} onChange={(e) => setData({ ...data, code: e.target.value.toUpperCase().replace(/\s+/g, "_") })} placeholder="VD: TECH_SCHOOLS" /></div></div><Select label="Nguồn bằng chứng trong CV" value={data.evidenceSource} onChange={(evidenceSource) => setData({ ...data, evidenceSource })} options={Object.entries(sourceLabel)} /><div><label className="mb-2 block text-sm font-medium">Thành viên trong nhóm</label><div className="max-h-56 space-y-2 overflow-y-auto rounded-lg border border-border p-3">{organizations.map((org) => <label key={org.id} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={data.memberIds.includes(org.id)} onChange={() => toggle(org.id)} /><span>{org.name}</span><span className="text-xs text-muted">{org.type}</span></label>)}</div></div><div className="flex justify-end gap-2"><Button variant="secondary" onClick={onClose}>Hủy</Button><Button loading={save.isPending} onClick={() => save.mutateAsync({ id: item?.id, data }).then(() => { toast.success("Đã lưu nhóm đối chiếu"); onClose(); })}>Lưu nhóm</Button></div></div></DialogContent></Dialog>;
}

function Select({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: string[][] }) { return <div><label className="mb-1 block text-sm font-medium">{label}</label><select className="h-10 w-full rounded-[9px] border border-border-strong bg-surface px-3 text-sm" value={value} onChange={(e) => onChange(e.target.value)}>{options.map(([key, name]) => <option key={key} value={key}>{name}</option>)}</select></div>; }
